ci: Try handle nuspec version

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -10,11 +10,37 @@ pool:
   vmImage: 'windows-latest'
 
 variables:
-  solution: '**/*.sln'
-  buildPlatform: 'Any CPU'
-  buildConfiguration: 'Release'
+- group: LatestPackageVersions
+- name: solution
+  value: '**/*.sln'
+- name: buildPlatform
+  value: 'Any CPU'
+- name: buildConfiguration
+  value: 'Release'
 
 steps:
+
+- task: Bash@3
+  inputs:
+    targetType: 'inline'
+    script: |
+              # Récupérer la valeur actuelle de la variable partagée
+              currentVersion=$(LatestPackageVersions.7.x.x)
+      
+              # Lire la version à partir du fichier nuspec
+              nuspecVersion=$(grep -oP '(?<=<version>)[^<]+' **/*.nuspec)
+      
+              echo "Current shared version: $currentVersion"
+              echo "Version from nuspec: $nuspecVersion"
+      
+              if [ "$currentVersion" == "$nuspecVersion" ]; then
+                echo "Error: Version needs to be updated!"
+                exit 1
+              else
+                echo "Versions are different. Updating shared variable..."
+                echo "##vso[task.setvariable variable=LatestPackageVersions.7.x.x;isOutput=true]$nuspecVersion"
+              fi
+
 - task: NuGetToolInstaller@1
 
 - task: NuGetCommand@2
@@ -31,6 +57,12 @@ steps:
   inputs:
     platform: '$(buildPlatform)'
     configuration: '$(buildConfiguration)'
+
+- task: NuGetCommand@2
+  inputs:
+    command: 'pack'
+    packagesToPack: '**/*.nuspec'
+    versioningScheme: 'off'
 
 - task: PublishBuildArtifacts@1
   inputs:
