ci: New version should be greater than latest

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -38,9 +38,42 @@ steps:
 
               echo "Latest version was $latestVersion"
               echo "Version from nuspec is $nuspecVersion"
+
+              function Compare-SemanticVersions {
+                param (
+                    [string]$latestVersion,
+                    [string]$newVersion
+                )
+
+                $latestVersionArray = $latestVersion -split '\.'
+                $newVersionArray = $newVersion -split '\.'
+
+                $length = [Math]::Max($latestVersionArray.Length, $newVersionArray.Length)
+
+                for ($i = 0; $i -lt $length; $i++) {
+                    $part1 = if ($i -lt $latestVersionArray.Length) { [int]$latestVersionArray[$i] } else { 0 }
+                    $part2 = if ($i -lt $newVersionArray.Length) { [int]$newVersionArray[$i] } else { 0 }
+
+                    if ($part1 -lt $part2) {
+                        return -1
+                    }
+                    elseif ($part1 -gt $part2) {
+                        return 1
+                    }
+                }
+                return 0
+              }
+
+              $result = Compare-SemanticVersions -latestVersion $latestVersion -newVersion $newVersion
+              if ($result -le 0) {
+                echo "ERROR: new version (nuspec version) should be greater than latest version."
+                echo "You must update the version number in the nuspec file to continue."
+                exit 1
+              }
       
               if [ "$latestVersion" == "$nuspecVersion" ]; then
-                echo "Error: Version needs to be updated!"
+                echo "ERROR: new version (nuspec version) should be greater than latest version."
+                echo "You must update the version number in the nuspec file to continue."
                 exit 1
               else
                 echo "Versions are different. Updating shared variable..."
